# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51e95e3c4883dae90629dead2ea50b88d9b70e304350822d01e34ee388b81317dcd652a7fde402d1164b69aa15449fb4e5113c55f8596a49d079a3c6d9040cb3

test:
  secret_key_base: cf4b09e09824389a93cbcf1cdd42e4cdc76816c54e1688d728c0a2e8de2f047ed8f6568a963ba010159547e40f2bcc12b67eb02e03dd369b9a27958dcd812095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
