AllCops:
  DisplayCopNames: true
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
   - 'spec/test_app/**/*'
  Include:
    - 'lib/tasks/**/*'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  TargetRubyVersion: 2.3
Documentation:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'
Metrics/BlockLength:
  Exclude:
    - config/environments/production.rb
    - '**/*_spec.rb'
    - 'spec/shared/**'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'
Lint/Debugger:
  Enabled: false
Lint/DefEndAlignment:
  AutoCorrect: true
Lint/EndAlignment:
  AutoCorrect: true
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
